function drawCircle(x,y,r,c,lineColor,lineWidth)
	if (nargin<=4)
		rectangle('Position',[x,y,r,r],'Curvature',[1 1],...
					'FaceColor',c,'EdgeColor','k');
	else
		rectangle('Position',[x,y,r,r],'Curvature',[1 1],...
					'FaceColor',c,'EdgeColor','k',...
					'EdgeColor',lineColor,...
					'LineWidth',lineWidth...
					);
	end
end